# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.get_image_path),
        ),
    ]
